### ISSUE TITLE
Error when executing DiscordManager.smartGetToken()

### ISSUE THREAD

**Issue by Mr-Pine** [MeixDev/DiscordManager#1]
The error
```ps
I/flutter (14462): Getting Refreshed Token
E/flutter (14462): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method '-' was called on null.
E/flutter (14462): Receiver: null
E/flutter (14462): Tried calling: -(800)
E/flutter (14462): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (14462): #1      new DiscordCredentials (package:discord_manager/models/discord_credentials.dart:15:73)
E/flutter (14462): #2      new DiscordCredentials.fromJson (package:discord_manager/models/discord_credentials.dart:66:7)
E/flutter (14462): #3      new DiscordCredentials.fromRawJson (package:discord_manager/models/discord_credentials.dart:59:26)
E/flutter (14462): #4      DiscordManager._getToken (package:discord_manager/discord_manager.dart:262:40)
E/flutter (14462): <asynchronous suspension>
E/flutter (14462): #5      DiscordManager.refreshToken (package:discord_manager/discord_manager.dart:277:12)
E/flutter (14462): #6      DiscordManager.smartGetToken (package:discord_manager/discord_manager.dart:285:14)
E/flutter (14462): #7      doAuthWorkflow (package:QuoteApp/oauth_2.dart:41:24)
E/flutter (14462): <asynchronous suspension>
E/flutter (14462): #8      CustomFormState.build.<anonymous closure> (package:QuoteApp/customForm.dart:342:21)
E/flutter (14462): #9      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
E/flutter (14462): #10     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
E/flutter (14462): #11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
E/flutter (14462): #12     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
E/flutter (14462): #13     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
E/flutter (14462): #14     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:219:7)
E/flutter (14462): #15     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:477:9)
E/flutter (14462): #16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:78:12)
E/flutter (14462): #17     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:124:9)
E/flutter (14462): #18     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (14462): #19     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:122:18)
E/flutter (14462): #20     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:108:7)
E/flutter (14462): #21     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:220:19)
E/flutter (14462): #22     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter (14462): #23     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
E/flutter (14462): #24     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
E/flutter (14462): #25     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
E/flutter (14462): #26     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (14462): #27     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (14462): #28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (14462): #29     _invoke1 (dart:ui/hooks.dart:267:10)
E/flutter (14462): #30     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
E/flutter (14462): 

```

**Comment by Mr-Pine** [comment]
Found the error! It was an old and therefore invalid refresh token. Maybe it would be a good idea to log this info to the console.

**Comment by MeixDev** [comment]
Thanks for the feedback ! I'll look into it to see how I could change it so it instead logs the fact that the refresh token is invalid, instead of straight up throwing an error.
